### ISSUE TITLE
nwayo doctor pour les versions alpha

### ISSUE THREAD

**Issue by benoitrenaud** [absolunet/nwayo-cli#1]
Dans le compte-rendu de nwayo doctor, il semble faire un copie de la version de Foundation pour celle JQuery alpha : 

Bower diagnosis
    You are a dull blade   ಠ_ಠ
    [foundation] : 5.5.2 ➝  5.5.3
    [jquery] : 2.1.4 ➝  **5.5.3**
    [kafe] : 3.0.1 ➝  3.0.3
    [modernizr] : 2.8.3 ➝  3.1.0
    [pubsub-js] : 1.5.2 ➝  1.5.3
....

**Comment by jblandry** [comment]
Corrigé : 04423e2618a5788e48e436cb0e93c07acecb227b
