### ISSUE TITLE
nwayo install commands not working (windows / cli 1.2.0)

### ISSUE THREAD

**Issue by fforget** [absolunet/nwayo-cli#10]
- Nothing happens when using `nwayo install workflow`
- `bower_components` folder is erased when using `nwayo install vendors`

**Comment by thierry2015** [comment]
Same here

**Comment by jblandry** [comment]
- Workflow corrected by 6767dda567c09dab7f1cf6fa9906a80ae19595ae
- Vendors corrected by https://github.com/absolunet/nwayo/commit/92d6f0e36577766c0cbfd7bb88643f3c7b6f886b
